config/routes.rb
Rails.application.routes.draw do
  root 'galleries#index'
  resources :galleries, only: [:index, :show, :new, :create] do
    resources :art_pieces, only: [:new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art_piece.rb
class ArtPiece < ApplicationRecord
  belongs_to :gallery

  validates_presence_of :title, :year, :artist
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  has_many :art_pieces

  validates :name, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true, length: {is: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/art_pieces_controller.rb
class ArtPiecesController < ApplicationController
  def new
    @gallery = Gallery.find(params[:gallery_id])
    @art_piece = ArtPiece.new
  end

  def create
    @gallery = Gallery.find(params[:gallery_id])
    @art_piece = ArtPiece.new(art_piece_params)
    @art_piece.gallery = @gallery

    if @art_piece.save
      flash[:notice] = "Painting added successfully"
      redirect_to gallery_path(@gallery)
    else
      flash[:alert] = @art_piece.errors.full_messages.to_sentence
      render :new 
   end
  end

  private

  def art_piece_params
    params.require(:art_piece).permit(:title, :year, :artist)

  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index
    @galleries = Gallery.all
  end

  def show
    @gallery = Gallery.find(params[:id])
    @art_pieces = @gallery.art_pieces
  end

  def new
    @gallery = Gallery.new
  end

  def create
    @gallery = Gallery.new(gallery_params)

    if @gallery.save
      flash[:notice] = "Gallery added successfully"
      redirect_to gallery_path(@gallery)
    else
      flash[:alert] = @gallery.errors.full_messages.to_sentence
      render :new
    end
  end

  private

  def gallery_params
    params.require(:gallery).permit(:name, :city, :state, :zip, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/art_pieces/new.html.erb
<h1>Painting Form for <%= @gallery.name %></h1>

<%= form_for [@gallery, @art_piece] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :year %>
  <%= f.text_field :year %>

  <%= f.label :artist %>
  <%= f.text_field :artist %>

  <%= f.submit "Add Art Piece" %>
<% end %>

app/views/galleries/index.html.erb
Just ok Galleries

<% @galleries.each do |gallery| %>
  <%= link_to "#{gallery.name}", gallery_path(gallery) %>
<% end %>

<%= link_to "Add New Gallery", new_gallery_path %>

app/views/galleries/new.html.erb
New Gallery Form

<%= form_for(@gallery) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.label :state %>
  <%= f.text_field :state %>

  <%= f.label :zip %>
  <%= f.text_field :zip %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit "Add Gallery" %>
<% end %>

app/views/galleries/show.html.erb
<h1><%= @gallery.name %></h1>
<%= @gallery.city %>
<%= @gallery.state %>
<%= @gallery.zip %>
<%= @gallery.description %>

<% @art_pieces.each do |art| %>
  <%= art.title %>
  <%= art.year %>
  <%= art.artist %>
  <%= art.created_at.strftime("%B %d %Y") %>
<% end %>

<%= link_to "Add Art Piece", new_gallery_art_piece_path(@gallery) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>gallery Reviews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <%= value %>
<% end %>

<%= yield %>

</body>
</html>